### ISSUE TITLE
Library must manage language supported

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#110]
- [x] When you inject the component in your  page using the library , you inform it about which language you need to support  and consequently for any language it will add a tab for this language automatically and automatically for this language generate the forms for it . This means that the name of the fields should be set automatically for the language supported.

**Acceptance testing**

- [x] Library should handle language management by automatically for each sections having the language tab supported by the component showing and the form corresponding to it.

**Comment by mahfouzhseineweev** [comment]
@jfayad The forms with the language switcher that is in blue in sections website for example, this is coming from the host project itself and not the library, and any new language that will be added by the host project. Consequently the support for it should be implemented and the translation files should be created. I am not seeing how can this be automatic and how is the library relevant in this case

**Comment by mahfouzhseineweev** [comment]
I just want to make I got this issue correctly:

The component we have now to switch the form languages 

<img width="455" alt="Screenshot 2023-06-09 at 9 12 39 AM" src="https://github.com/Geeks-Solutions/vue-sections/assets/101403093/7f48dfd4-035b-49e1-bd1f-cb22a07301c6">

* This component should be moved to the nuxt-sections library and it will show for any section type form that a dev user create. 

* The languages that will show in it will depend on a prop that will be given to the main Sections component by the dev user for example `:locales=['en', 'fr', 'es']`. Which will result in showing 3 tabs one for each langauge.

* By default this component will not be showing and we will add a prop to main Sections component to enable/disable it in case the dev user wants to add his own language switcher to his forms.

The above is the only work that will be on the library regarding this issue: Things like form fileds titles, generated forms for each language. These will be up to the dev user on the host project to implement based on his needs.

So there wont be a generated form for each language but instead, there will be one form that will have different v-models based on the selected language ie: `settings[lang].link` where lang value will be set when selecting it from the component coming from the nuxt-sections library.

And what about the translations of the library itself ? because currently it only has en and fr translations and I still don't know how it will behave if the host project has a third language support. But I guess the labels will show as translation keys. I don't think this can be automatically done to generate translations for those for a new language. 
But the dev user will always have the ability to add translations for the library from the host project if He just know the keys of these translations. What do you think ?


@jfayad Please let me know if all the above is valid so I can implement the correct feature needed as I don't want to be off topic when working it to not add features that are not what we need

**Comment by jfayad** [comment]
> The above is the only work that will be on the library regarding this issue: Things like form fileds titles, generated forms for each language. These will be up to the dev user on the host project to implement based on his needs.

Actually, the library will automatically provide the values for the translations. Basically it will shadow each field with a language key and that will be sent to sections when editing (and that will be returned to the section when displaying based on the selected language)

> And what about the translations of the library itself ? because currently it only has en and fr translations and I still don't know how it will behave if the host project has a third language support.

These are completely different stuff... It is possible to have the UI in english and provide a french translation (or any other translation)

**Comment by mahfouzhseineweev** [comment]
## Report:

So far I have moved the Translation component to the library as a first step, I made configurable to read the languages as a prop that will be fed by the host project.  I added it to the wysiwyg static section type provided by default by the library to test it The test was successfully for dynamically adding the the key for translations and save the sections with them however I faced some problems with content not loading when editing and another problem that the languages are only loading the default en and fr ones that are set to the prop and if I add an extra language from the host project using the prop, it is not showing as an extra tab in the translations component. So I will need a new Timebox to proceed with the tests and the implementations  For the multiple languages support if the project is using only dynamic pages, how can we feed the Sections Main component with the host project required languages that He wants to use ?

**Comment by mahfouzhseineweev** [comment]
## Report:

Problems that were faced in the first Timebox has been resolved, the locales languages are loaded in the wysiwyg static section and the the data are showing correctly for each language now.

Note: There is one point to be clarified that locales are similar to variations, so if a page has locales it should be specifically created on the host project and the locales prop should be fed with the required languages

There is no need for additional Timeboxes, I will need 2 hours to finalize this issue. After putting the Translation component inside the statuc wysiwyg section that comes with library => Next step will be to put the Translation component inside the page Metadata popup to select a language to fill titles and descriptions.

@jfayad The above is the only work required on the library that I thought of (The translation component in the static wysiwyg section and the in the popup of page Metadata)

**Comment by akramsarkis** [comment]
@mahfouzhseineweev ,

How do I test this issue ?  I mean I need to have language configured and then make sure they are reflected

**Comment by mahfouzhseineweev** [comment]
@akramsarkis You need to wait for the issue to be done, You will be able to test it by informing me what languages you want to be included in the site so I add them in the prop of Sections components that will relay them to the nuxt sections library
