### ISSUE TITLE
QA on layout issues

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#119]
- [x] When adding a wyzywig section using a layout then I save the page and refresh it I have server error showing

<img width="1426" alt="Screenshot 2023-10-04 at 12 43 56" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/fc04b4a2-caf7-444c-905b-0dfa762ffa3e">

- [x] When the section is added empty like the wyzywig one, using layout 2, it is not showing to edit it

- [x] When you add an empty wyzywig section then you add another wyzywig section not empty this time , you will see that the empty one is noi more showing and the new one cannot be moved
- [x] When selecting wrongslotsInTemplate, let's have the first letter of left region and right region in upper case

<img width="774" alt="Screenshot 2023-10-04 at 14 08 27" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/cfeba133-ea1e-4f0a-96c9-50a13ea8825f">

- [x] When deleting a section from a region, there is a typo in the error,  it should finish by " The section will be deleted from all layouts"

<img width="1073" alt="Screenshot 2023-10-04 at 14 09 56" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/ebdccc6e-e9e4-484f-921c-a45ec24a8327">

- [x] When using layout 1, the footer is showing twice

**Acceptance testing**

- [x] When adding a wyzywig section using a layout then I save the page and refresh it I have server error showing , i should have the page showing again
- [x] When the section is added empty like the wyzywig one, using layout 2, it is not showing to edit it, it should show
- [x] When you add an empty wyzywig section then you add another wyzywig section not empty this time , you will see that the empty one is no more showing and the new one cannot be moved, i should see the emoty one and should be able to move the other one
- [x] When selecting wrongslotsInTemplate, let's have the first letter of left region and right region in upper case
- [x] When deleting a section from a region, there is a typo in the error,  it should finish by " The section will be deleted from all layouts"
- [x] When using layout 1, the footer is showing twice, it should show once

**Comment by mahfouzhseineweev** [comment]
@akrams 

* I thought we agreed that the place of the dropdown is good regarding the first point and that the screenshot was misleading

* The performance is not affected by the Layout issue at all and these were the same before and we did the max we can do regarding this

* > When the option to highlight regions is selected if you check the image below you will see that on the right I need to scroll right to see it which is wrong

This is caused by the section type CSSs not being adapted to the Layouts, we are only installing Layouts on section website for testing and adapting the sections was not requested as this site will not be using Layouts

* > If the regions are empty, adjust their height and width (by injecting fake values) so the borders shows correctly and this is only while dragging: This is not applied

It is applied

<img width="2560" alt="Screenshot 2023-10-05 at 8 43 00 AM" src="https://github.com/Geeks-Solutions/vue-sections/assets/101403093/4b229e2f-7551-4e16-9764-cd13bdde95df">

**Comment by akramsarkis** [comment]
Hello @jfayad 

- Can you please check first point about the layout drop down position and let me know if it is ok as it is done now, in my side I am finding it good like this as we can directly see the layout chosen and its region once selecting it
- Can you check the second point about performance as per Hussein comment below, the layout has nothing to do with the performance i found, so i just need you to confirm this.

> The performance is not affected by the Layout issue at all and these were the same before and we did the max we can do regarding this

**Comment by akramsarkis** [comment]
All good closing it
