### ISSUE TITLE
Update the library of section front to have it use media

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#16]
- [x] Update the library of section front to have it use media
- This is because the last update of sections is to use media, so the front library should be updated to be able use this last change

**Comment by mahfouzhseineweev** [comment]
The issue took more time then expected because of the wysiwyg update which needed a specific update to have it use media as well with its same button of uploading an image, in addition to the debug time of building the library each time then removing it from package-lock of the host project and rerun it to test the update
