### ISSUE TITLE
Fix the display of configurable sections when opening it

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#71]
- [ ] When there is configurable section, it is showing like below instead of showing the fields correctly, you can use the notification website project on sections where we added this section:

<img width="1051" alt="Screenshot 2023-02-13 at 17 43 58" src="https://user-images.githubusercontent.com/82215775/218504091-256bb5b9-d836-4b8f-b9c5-fa0c5dd54e73.png">

**Comment by mahfouzhseineweev** [comment]
The issue took more than expected and still needs 1.5h to be completed because the following:

The estimation time was based on the fact that there is just a bug in the display of the configurable section on the library that needs to be fixed, but I found that the configurable section was not working at all and it was reading the fields in a wrong way and also was missing the support of multiple type fields to display the correct form. So as result the implementation took more time to fix the section and support the fields types and still needs more time to complete it

**Comment by akramsarkis** [comment]
All good, can be closed
