### ISSUE TITLE
Import/ export sections or pages 

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#75]
- [ ] We need an option to be able import and export sections or pages to not have to recreate from scratch when moving to prod. This issue needs to be groomed

**Comment by akramsarkis** [comment]
@jfayad  here the issue for the import/ export to groom

**Comment by akramsarkis** [comment]
@mahfouzhseineweev ,

- [ ] When Imported I saw a warning message about the configurable section to authorize it, is this normal ? Nor problem but i just want to make sure this is ok
- [ ] However when importing, it didn't import the background of the first section that is included in the section
- [ ] Now it is not as well showing the background of the rest, I know it is not part of the sections, but how if someone moves from dev to prod, he will be able to have the exact same page ? Shouldn't the css on the sections be imported as well ?

**Comment by mahfouzhseineweev** [comment]
@akramsarkis for the 1st the warning was requested by Julien on sections channel.
for the 2nd and rd point the background is part of the page so the dev will be responsible of updating it on the page He wants. The issue is only about exporting importing the sections themself. So if you find a missing peace of these sections then that should be reported. Ottherwise the rest is normal

**Comment by akramsarkis** [comment]
Well @hussein661 in the first section again there is missing the backgroudn image, if you edit the section, you are uploading it there

**Comment by mahfouzhseineweev** [comment]
It is not part of the section @akramsarkis is it ?

**Comment by akramsarkis** [comment]
all good now, this can be closed
